services:
  - type: web
    name: project-pulse-python-server
    runtime: python
    rootDir: pythonPulse
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: PORT
        value: 8000
      - key: ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GUILD_ID
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
    # Optional: If you want to use a specific Python version
    # envVars:
    #   - key: PYTHON_VERSION
    #     value: 3.10.0
